chore: pull request template
alcpereira/100hunters pull request #32
Opened 2024-03-15 20:22 UTC by Pankeking

2024-03-16 13:13 UTC, alcpereira requested changes
As discussed in DM, the template should be a bit more complete and styled.

2024-03-16 19:31 UTC, alcpereira approved these changes

2024-03-17 10:47 UTC, alcpereira requested changes
Do you mind updating the branch to the last version we revised together please?

2024-03-17 11:21 UTC, Pankeking commented
> Do you mind updating the branch to the last version we revised together please?

I didn't push it last night, it should be updated now

2024-03-17 11:29 UTC, alcpereira approved these changes
Great job 💪

2024-03-17 11:29 UTC, alcpereira commented on .env.example
This change should be undone.

2024-03-17 11:31 UTC, Pankeking commented on .env.example
what is an optimal way to undo a change?

2024-03-17 12:27 UTC, Kenspectacle requested changes
Looks about right to me so far!

Though I am not exactly sure what you meant by "Documentation is updated" in the Reviewer Checklist, maybe a slight more detail/rewording there?

2024-03-17 12:33 UTC, Pankeking commented
> Looks about right to me so far!
> 
> Though I am not exactly sure what you meant by "Documentation is updated" in the Reviewer Checklist, maybe a slight more detail/rewording there?

"Documentation regarding the PR has been properly updated"
Is this clearer?
Any suggestion welcome

2024-03-17 12:44 UTC, Kenspectacle commented
> > Looks about right to me so far!
> > Though I am not exactly sure what you meant by "Documentation is updated" in the Reviewer Checklist, maybe a slight more detail/rewording there?
> 
> "Documentation regarding the PR has been properly updated" Is this clearer? Any suggestion welcome

Nice, it makes much more sense to me! :)

2024-03-17 13:31 UTC, Kenspectacle approved these changes
LGTM :shipit:

2024-03-17 14:01 UTC, closed without merging