feat: unit testing React components
alcpereira/100hunters pull request #36
Opened 2024-03-16 16:14 UTC by CharlesErrington

2024-03-16 16:43 UTC, alcpereira requested changes
Good job 💪 

Some nitpicks and additional investigation to be done.

2024-03-16 16:43 UTC, alcpereira commented on app/components/Card/Card.test.tsx
> +import "@testing-library/jest-dom";
This should belong to `tests/setup.ts` (see [here](https://www.npmjs.com/package/@testing-library/jest-dom#with-vitest)).

Do you mind checking if everything works well without this import?

2024-03-16 16:43 UTC, alcpereira commented on app/components/Card/Card.test.tsx
> +    screen.debug();
Maybe leave this comment and command in the documentation.

2024-03-16 16:43 UTC, alcpereira commented on app/components/Card/Card.test.tsx
> +    expect(screen.getByTestId("card-body")).toHaveTextContent("world");
Based on [guiding principles](https://testing-library.com/docs/queries/about#priority), `data-testid` is not recommended for React Testing Library, it's on purpose the last on the list.

We could also reinforce this in the docs regarding testing React components.

For reference:
- Testing library and Playwright are against using `data-testid`
- Cypress recommends it

2024-03-16 16:43 UTC, alcpereira commented on app/components/Card/Card.tsx
> +      <p data-testid="card-body">{content}</p>
Same comment regarding `data-testid` with React Testing Library.

2024-03-16 16:43 UTC, alcpereira commented on app/components/Column/Column.tsx
> +      className="border-1 rounded-md border border-solid border-gray-700 px-2 py-5"
Hopefully this will be fixed in #34 , my bad 🙏

2024-03-16 16:43 UTC, alcpereira commented on app/components/Column/Column.tsx
> +      <h1 data-testid="column-title">This is a column</h1>
Same for `data-testid`

2024-03-16 16:43 UTC, alcpereira commented on package.json
Do you mind rebasing with the branch `feat/unit-test` please? You can point this PR to #29

2024-03-16 16:43 UTC, alcpereira commented on vite.config.ts
I guess we should create another Vite config for this, like I did for Storybook.
You need to import the plugin `react()` from `@vitejs/plugin-react` and if it's like Storybook the `remix()` plugin will cause issues.

Do you mind investigating how it would work with the PR already opened for Vitest?

2024-03-19 19:32 UTC, CharlesErrington commented on app/components/Card/Card.test.tsx
> +    expect(screen.getByTestId("card-body")).toHaveTextContent("world");
changed

2024-03-19 19:33 UTC, CharlesErrington commented on app/components/Card/Card.test.tsx
> +    screen.debug();
will do!

2024-03-19 19:33 UTC, CharlesErrington commented on app/components/Card/Card.test.tsx
> +import "@testing-library/jest-dom";
removed

2024-03-19 19:35 UTC, CharlesErrington commented on app/components/Column/Column.tsx
> +      <h1 data-testid="column-title">This is a column</h1>
removed

2024-03-19 19:35 UTC, CharlesErrington commented on app/components/Card/Card.tsx
> +      <p data-testid="card-body">{content}</p>
removed

2024-03-19 20:56 UTC, alcpereira commented
Reopening in another PR

2024-03-19 20:56 UTC, closed without merging